### ISSUE TITLE
The `About Me` page doesn't mention your undertakings at UNM.

### ISSUE THREAD

**Issue by sarojkh** [veeshanr/veeshanr.github.io#1]
I notice the `Contact:` section mentions your ties with UNM, but the description content doesn't. The second paragraph talks about BAC, and third para directly jumps to NDSU. Fill the gap maybe.

**Comment by sarojkh** [comment]
@veeshanr ^^^

**Comment by nrayamajhee** [comment]
I think he's gonna change the contact sidebar because he's moving to North State Dakota University.
